### ISSUE TITLE
License Change (MIT -> Commercial)

### ISSUE THREAD

**Issue by jonah512** [jonah512/jomock#11]
@Sudarshan-Bisht @Contilehpat 
Hi,
I'd like to ask your opinion about changing the license of **jomock** project from MIT to dual license of LGPL2.0 for individual and a Commercial for companies(commercial use).

**Comment by Contilehpat** [comment]
Hi @jonah512,

I would not change the license as unit tests are usually not part of a delivery/release. And the usual discussion on FOSS licenses is only on releases.

A license change can only be done in newer versions.

**Comment by jonah512** [comment]
@Contilehpat 
Thank you for your quick response.

The new version(2.x) could be released with a new license.
I'm wondering if you want to join "the commercialization of the jomock" as a contributor.
Contributors could be a contractor of Jomock project and get part of the profit as well.

**Comment by Contilehpat** [comment]
@jonah512 
Sorry, but first I see no bussiness opertunity in there, because nearly no one will release his commercial software together with the unit tests, so LGPL usage will not be an issue for most of the companies. 

Second, I see a declining popularity in C++ in the future in favour to e.g. Rust. As a result the market will shrink.

Third, I don't see much popularity on the project, so gathering customers will be hard.

Finally, being a contractor would result in much more paper work(tax stuff).
